### ISSUE TITLE
[Bug]: mod slows down and breaks chunkloading

### ISSUE THREAD

**Issue by Nycto97** [someaddons/betterchunkloading#4]
### Describe the bug you're experiencing

Whenever I have this mod installed, chunkloading seems worse/slower than before, especially when generating new chunks + there are missing chunks not loading in.

Chunks missing:
![2023-10-09_07 42 45](https://github.com/someaddons/betterchunkloading/assets/83367226/28cbd41b-2037-4725-8bd2-7274e2f77323)

Chunks disappearing:
![image](https://github.com/someaddons/betterchunkloading/assets/83367226/d1d7d359-00c1-43f5-8772-84a76ed8e27b)
After moving slightly to the right:
![image](https://github.com/someaddons/betterchunkloading/assets/83367226/c2713c19-3e47-4666-85db-b4033451e156)

### Reproducability

Just have the mod loaded along with these mods on the server:
Mod list text: [mod-list_2023-10-09_07.51.19.txt](https://github.com/someaddons/betterchunkloading/files/12842962/mod-list_2023-10-09_07.51.19.txt)
Mod list zip: https://we.tl/t-8jL2c2qJP0
Config file: https://pastebin.com/YqjaVsCd

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/Nycto97/75ae219d17361c1e43702c16293e4635

**Comment by Nycto97** [comment]
latest.log line 5625

```
[09Oct2023 07:39:46.439] [pool-12-thread-1/ERROR] [ModernFix/]: Async chunk load took way too long, this needs to be reported to the appropriate mod.
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.handler$zdd000$bailIfServerDead(ServerChunkCache.java:1618) ~[server-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java) ~[server-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:179) ~[server-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129) ~[server-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.mehvahdjukaar.supplementaries.common.worldgen.StructureLocator.getStructuresAtChunkPos(StructureLocator.java:227) ~[supplementaries-1.19.2-2.3.24.jar%23711!/:?]
	at net.mehvahdjukaar.supplementaries.common.worldgen.StructureLocator.findNearestMapFeatures(StructureLocator.java:170) ~[supplementaries-1.19.2-2.3.24.jar%23711!/:?]
	at net.mehvahdjukaar.supplementaries.common.block.tiles.BlockGeneratorBlockTile.lambda$tick$0(BlockGeneratorBlockTile.java:49) ~[supplementaries-1.19.2-2.3.24.jar%23711!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by someaddons** [comment]
its supplementaries slowing the server in your log, unrelated to better chunk loading. Chunks visually missing is part of rendering which this mod also doesnt touch

**Comment by Nycto97** [comment]
I'd like to point out that these issues only occur whenever BCL is installed.
Having Supplementaries, along with hundreds of other mods, installed, does not cause these issues.
Installing BCL on top will slow down chunkloading + cause missing chunks.

But indeed, like you said, it looks like it's a Supplementaries issue.

**Comment by mateus3c** [comment]
Im having the exact same issue, it took me days to figure out I had to remove Better Chunk Loading to fix it. My game was also loading super slow and having missing chunks. Removing BCL fixed it.

**Comment by APrimevalWorld** [comment]
Can confirm this is still a problem, even without Supplementaries. 1.19.2, crashes with the same log. I suspect it's a mod incompatibility, because it was fine a while back... but now it's not.
